config/routes.rb
Rails.application.routes.draw do
  root 'datetimes#index'
  devise_for :users
  resources :datetimes
  
end

app/models/datetime.rb
class Datetime < ActiveRecord::Base
	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :datetime
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/datetimes_controller.rb
class DatetimesController < ApplicationController
  before_action :set_datetime, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  # GET /datetimes
  # GET /datetimes.json
  def index
    @datetimes = Datetime.all
  end
  

  # GET /datetimes/1
  # GET /datetimes/1.json
  def show
  end

  # GET /datetimes/new
  def new
    @datetime = Datetime.new
  end

  # GET /datetimes/1/edit
  def edit
  end

  # POST /datetimes
  # POST /datetimes.json
  def create
    @datetime = Datetime.new(datetime_params)

    respond_to do |format|
      if @datetime.save
        format.html { redirect_to @datetime, notice: 'Datetime was successfully created.' }
        format.json { render :show, status: :created, location: @datetime }
      else
        format.html { render :new }
        format.json { render json: @datetime.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /datetimes/1
  # PATCH/PUT /datetimes/1.json
  def update
    respond_to do |format|
      if @datetime.update(datetime_params)
        format.html { redirect_to @datetime, notice: 'Datetime was successfully updated.' }
        format.json { render :show, status: :ok, location: @datetime }
      else
        format.html { render :edit }
        format.json { render json: @datetime.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /datetimes/1
  # DELETE /datetimes/1.json
  def destroy
    @datetime.destroy
    respond_to do |format|
      format.html { redirect_to datetimes_url, notice: 'Datetime was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_datetime
      @datetime = Datetime.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def datetime_params
      params.require(:datetime).permit(:name, :lastname, :startdate, :enddate)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/datetimes_helper.rb
module DatetimesHelper
end

app/views/datetimes/_form.html.erb
<%= form_for(@datetime) do |f| %>
  <% if @datetime.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@datetime.errors.count, "error") %> prohibited this datetime from being saved:</h2>

      <ul>
      <% @datetime.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <input type="text" class="col-lg-5" name="daterange"/>
  
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :lastname %><br>
    <%= f.text_field :lastname %>
  </div>
  <div class="field">
    <%= f.label :startdate %><br>
    <%= f.date_select :startdate %>
  </div>
  <div class="field">
    <%= f.label :enddate %><br>
    <%= f.date_select :enddate %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>



<script type="text/javascript">

var hash = {
            "Today": ["2017-01-30 00:00", "2017-01-30 23:59"],
            "Yesterday": ["2017-01-29 00:00", "2017-01-29 23:59"],
            "Last 7 days": ["2017-01-23 00:00", "2017-01-30 23:59"]
        };
$(function() {
    $('input[name="daterange"]').daterangepicker({
        timePicker: true,
        timePickerIncrement: 30,
        locale: {
            format: 'YYYY-MM-DD h:mm'
        },
        ranges: hash    
    });
    
    $(window).scroll(function() {
      if ($('input[name="daterange"]').length) {
          $('input[name="daterange"]').daterangepicker("close");
      }
    });
});
</script>

app/views/datetimes/edit.html.erb
<h1>Editing Datetime</h1>

<%= render 'form' %>

<%= link_to 'Show', @datetime %> |
<%= link_to 'Back', datetimes_path %>

app/views/datetimes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Datetimes</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Lastname</th>
      <th>Startdate</th>
      <th>Enddate</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @datetimes.each do |datetime| %>
      <tr>
        <td><%= datetime.name %></td>
        <td><%= datetime.lastname %></td>
        <td><%= datetime.startdate %></td>
        <td><%= datetime.enddate %></td>
        <td><%= link_to 'Show', datetime %></td>
        <td><%= link_to 'Edit', edit_datetime_path(datetime) %></td>
        <td><%= link_to 'Destroy', datetime, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Datetime', new_datetime_path %>



    <div class="container">
      <!-- Example row of columns -->
      <div class="row">
        <div class="col-md-4">
          <h2>Heading</h2>
          <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
          <p><a class="btn btn-default" href="#" role="button">View details &raquo;</a></p>
        </div>
        <div class="col-md-4">
          <h2>Heading</h2>
          <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
          <p><a class="btn btn-default" href="#" role="button">View details &raquo;</a></p>
       </div>
        <div class="col-md-4">
          <h2>Heading</h2>
          <p>Donec sed odio dui. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Vestibulum id ligula porta felis euismod semper. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.</p>
          <p><a class="btn btn-default" href="#" role="button">View details &raquo;</a></p>
        </div>
      </div>

app/views/datetimes/new.html.erb
<h1>New Datetime</h1>

<%= render 'form' %>

<%= link_to 'Back', datetimes_path %>

app/views/datetimes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @datetime.name %>
</p>

<p>
  <strong>Lastname:</strong>
  <%= @datetime.lastname %>
</p>

<p>
  <strong>Startdate:</strong>
  <%= @datetime.startdate %>
</p>

<p>
  <strong>Enddate:</strong>
  <%= @datetime.enddate %>
</p>

<%= link_to 'Edit', edit_datetime_path(@datetime) %> |
<%= link_to 'Back', datetimes_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Datetime1</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
 <!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
 <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Project DateTime</a>
        </div>

        <div id="navbar" class="navbar-collapse collapse">
          <form class="navbar-form navbar-right">
            <div class="form-group"><%= link_to "SignIn", new_user_session_path %>
            </div>
            <div class="form-group"><%= link_to "SignUp", new_user_registration_path %></div>
          </form>
        </div><!--/.navbar-collapse -->
      </div>
    </nav>
  <div class="col-lg-12">
    
    <% if user_signed_in? %>  
      <%= current_user.email %>
      <%= link_to "signout", destroy_user_session_path, method: :delete %>
    <% else %>
      <%= link_to "signin", new_user_session_path %>
    <% end %>
      <%= yield %>
  </div>

<footer>
        <p>&copy; 2016 Company, Inc.</p>
      </footer>
</body>
</html>